config/routes.rb
Rails.application.routes.draw do

  resources :feeds
  resources :contents, only: [:index, :show]
  root 'feeds#index'

end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :feed
end

app/models/feed.rb
require 'feed'
class Feed < ActiveRecord::Base
  has_many :contents, dependent: :destroy
  after_create do
    FeedData.update_feed(url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
require 'feed'
class ContentsController < ApplicationController
  before_action :set_feed, only: :index
  def index
    @feeds.each do |feed|
      FeedData.update_feeds_contents(feed)
    end
    @contents = Content.all.order('published desc')
  end

  def show
    @content = Content.find(params[:id])
  end

  private

  def set_feed
    @feeds = Feed.all
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:title, :url, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/contents/index.html.erb
<div class="container">
  <% @contents.each do |content| %>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= link_to content.title, content %> - <i> published <%= time_ago_in_words(content.published) %> ago.</i>
      </div>
    </div>
  <% end %>
</div>

app/views/contents/show.html.erb
<div class="container">
  <h3><%= link_to @content.title, @content.url %></h3>
  <i>published on <%= @content.published %> by <%= @content.author %></i>
  <p>
    <%= @content.description.html_safe %>
  </p>
</div>

app/views/feeds/_form.html.erb
<%= form_for @feed, :html => { :class => "form-horizontal feed" } do |f| %>

  <% if @feed.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @feed.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:url) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                feeds_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/feeds/edit.html.erb
<%- model_class = Feed -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/feeds/index.html.erb
<%- model_class = Feed -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= link_to feed.id, feed_path(feed) %></td>
        <td><%= feed.title %></td>
        <td><%= feed.url %></td>
        <td><%= feed.description %></td>
        <td><%=l feed.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_feed_path(feed), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      feed_path(feed),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_feed_path,
            :class => 'btn btn-primary' %>
<%= link_to t('.reader'),
            contents_path,
            :class => 'btn btn-primary' %>

app/views/feeds/new.html.erb
<%- model_class = Feed -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/feeds/show.html.erb
<%- model_class = Feed -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @feed.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @feed.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @feed.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              feeds_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_feed_path(@feed), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              feed_path(@feed),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RssReader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>